"""add staff role

Revision ID: 310836efd034
Revises: b429e9f9df39
Create Date: 2026-08-06 15:22:52.872463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '310836efd034'
down_revision = 'b429e9f9df39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('student', 'admin'),
               type_=sa.Enum('student', 'admin', 'staff', name='user_role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('student', 'admin', 'staff', name='user_role'),
               type_=mysql.ENUM('student', 'admin'),
               existing_nullable=False)

    # ### end Alembic commands ###
